language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
before_install: cd ./api
install:
  - npm install
script:
  - npm run test
after_success: 
  - npm run coverage
env: 
global:
  -- CODECLIMATE_REPO_TOKEN=c14abfc89b0eb06fcb10f480f4b3e47142ac181c60c21f0131b570e72b1fbeb7