--- 
addons: 
  chrome: stable
after_script: 
  - "./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT"
after_success: 
  - "npm run coverage"
before_script: 
  - "npm i -g nyc"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
cache: 
  directories: 
    - node_modules
dist: trusty
env: 
  global: 
    - CC_TEST_REPORTER_ID=9aa8ff7fcdb7e404fbd4a0ff7c5a30f07577fd4e5681de577296a3984e9683dc
install: 
  - "npm install"
language: node_js
node_js: 
  - "8.2.1"
notifications: 
  email: true
script: 
  - "npm run test"
services: 
  - postgresql
